name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Log in to Docker Hub using GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      # Build Docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ujjwaltiwariii/test:latest

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ujjwaltiwariii/test:latest
